### ISSUE TITLE
Error: request timed out

### ISSUE THREAD

**Issue by apas** [kristofa/bookmarker_for_pinboard#21]
Lately, when I try to bookmark a URL the first try always fails with the following error: "Got an error when invoking request to api.pinboard.in: The request timed out."

If I try to bookmark the URL again it works.

<img width="326" alt="image" src="https://user-images.githubusercontent.com/347450/66370217-0b9b1080-e9a8-11e9-919e-c25fd515e566.png">

**Comment by kristofa** [comment]
Thanks for reporting. I had it a few times myself but not that often.

You'll get this error when there is no response from the Pinboard API within 1 second. This can be caused by your Internet connectivity or the Pinboard servers that are slower to respond or both.
  
I'll increase the timeout in a next release version so you're less likely to get the error.

**Comment by apas** [comment]
I still get this very frequently across a wide variety of Wi-Fi networks and different ISPs. Are you calling the Pinboard API upon button or keyboard shortcut press or when the pop-up has finished drawing?

**Comment by kristofa** [comment]
Since the last version we're calling the Pinboard API also when opening the pop-up because we request if the bookmark already exists and if that's the case we show the previously submitted data. This request almost never timed out for me but the request might be slower in case you have more bookmarks, not sure.  

I'll make a new release with an increased timeout because I understand it has a big impact on productivity and usability.

**Comment by kristofa** [comment]
@apas I submitted version v1.8 to the App Store for review. It should become available in one of the next days. The only change is an increase in timeout for both API requests:
 
   * looking up if a bookmark already exists: updated timeout from 1 second to 3 seconds.
   * adding a new bookmark: updated timeout from 1 second to 2 seconds.  

Let me know if this fixes the timeout errors you get once you tried it.

**Comment by kristofa** [comment]
@apas Version 1.8 is out for about a week now. Did you had a chance to try it out?

**Comment by apas** [comment]
I don't think I've seen it but didn't test much.

However, I was thinking: the biggest UX problem is not the error itself but the waiting time for any data to appear on the pop-up (bc checking if bookmark exists.) I think this can be improved to a near-instant load (after all, the payload is a few kb) but not sure what the best approach is.

**Comment by kristofa** [comment]
I know that updating the UI is slower now because the retrieval of a potentially existing bookmark takes time. I don't have control over improving the latency of the pinboard api. 

What do you think about populating the URL and title first and updating it in case the pinboard API returns an already bookmarked version?

**Comment by apas** [comment]
> What do you think about populating the URL and title first and updating it in case the pinboard API returns an already bookmarked version?

Sounds much better. UI should be instantly populated.

**Comment by kristofa** [comment]
I did an update so the URL and title are immediately populated and we are not waiting for the pinboard API to return. I plan on creating a new release by latest the end of the week.

**Comment by kristofa** [comment]
Update is submitted to the App Store, v1.9
