### ISSUE TITLE
Bookmarker fails if saved tag is selected

### ISSUE THREAD

**Issue by Threepwood42** [kristofa/bookmarker_for_pinboard#32]
Since moving to an M1 MacBook (Safari 15.6.1). I find that if I select a tag from the dropdown, the bookmarker invariably closes without saving the link to Pinboard. The link is correctly saved if I type in the tag.

**Comment by kristofa** [comment]
If you say 'select a tag from the dropdown' do you mean selecting it with the keyboard using `<arrow down>`, next `<arrow right>` or do you mean selecting the tag using the mouse cursor? 

Because selecting the tag using the mouse cursor indeed closes to window regardless of which architecture or Safari version you use. This seems to be a limitation of the dropdown implementation. Selecting the tag using the keyboard works for me and I'm using a M1 Pro Macbook also using Safari 15.6.1.

**Comment by Threepwood42** [comment]
Thank you Kristof, you are correct.

I feel more than a little stupid for not checking this method myself.......

Regards

Geoff Norman

--
  Geoff Norman
  ***@***.***

**Comment by kristofa** [comment]
You're not the first one who asked why selecting a tag doesn't work with the mouse. 

I'm using the auto-complete support from `NSControlTextEditingDelegate` and I'm not sure if that doesn't support selecting a tag with the mouse or if it is due to the extension popover. 

But anyway, it was not a stupid question at all :-)
