### ISSUE TITLE
Fill description from selection

### ISSUE THREAD

**Issue by mcg** [kristofa/bookmarker_for_pinboard#7]
First of all, thank you for making this!

If possible, please consider adding the ability to use the currently selected text from the page being bookmarked as the description of the bookmark.

**Comment by kristofa** [comment]
Thank you for reaching out @mcg. I like this feature request. I'll need some time to investigate how easy it is to get the selected text from the current active page. I'll hope to be able to do this soon and update here.

**Comment by kristofa** [comment]
@mcg This request has been implemented. It is part of a new version (1.4) that I just submitted for review to the App Store. I hope it becomes available soon.

**Comment by apas** [comment]
Just updated from the App Store. Had to re-enable the extension and restart Safari but works. One caveat for the next version: make the `Description` text field, if possible, scrollable. Say, I select a paragraph or two, it's very hard to have an confirmatory overview of what I previously selected; the only way currently to scroll is click in the text field, select text, and drag.

**Comment by kristofa** [comment]
@apas Re-enabling the extension and restarting Safari is required because the extension needs permission to read webpage content because I introduced a script that is injected in webpages to support capturing the selected text.

Making the Description field scrollable is again a great suggestion that I overlooked because I didn't select large sections of text while testing.
